### ISSUE TITLE
Kosmos and atmosphere are outdated

### ISSUE THREAD

**Issue by Mariostell** [noahc3/SDSetup#151]
The Kosmos/atmosphere version are outdated. The newest ones are 15.2 for kosmos and 0.10.3 for atmosphere. Those versions are really important because they support the latest Switch version 9.2.0

**Comment by hax4dazy** [comment]
Did you redownload the zip from github and not sdsetup.com?

**Comment by Mariostell** [comment]
I had to download the files from the Kosmos' GitHub page. Those files are working but SDSetup is faster and easier

**Comment by hax4dazy** [comment]
Also the sdsetup site always lags behind.

**Comment by Mariostell** [comment]
At the moment, I'm using Microsoft Edge and The site is working

**Comment by hax4dazy** [comment]
That's not what i meant. I meant that the site always takes some time to update the package

**Comment by Mariostell** [comment]
Ok, sorry, I'm Spanish and my english is not very good 👍

**Comment by noahc3** [comment]
Most stuff should be updated, I'll leave this open until I get a chance to add the Tesla stuff.

**Comment by 1046329594** [comment]
Should also update Hekate to support HOS 9.2.0

**Comment by noahc3** [comment]
Going through all of the packages now and will get them updated later tonight.

**Comment by noahc3** [comment]
## Changelog

The following packages were added:
* Tesla (telsa menu and nx-ovlloader)
  * Tesla is an option under Atmosphere options. Selecting it will show another category to add Tesla overlays.
* Status Monitor Overlay
* ovlSysmodules

The following packages are now configured to auto-update:
* Hekate (autoupdates from Kosmos) - Updated to v5.1.2
* lockpick_rcm (autoupdates from Kosmos) - Updated to v1.8.1
* pplay (autoupdates from Switchbru Appstore) - Updated to v3.1
* psnes (autoupdates from Switchbru Appstore) - Updated to v3.4

The following packages were manually updated:
* Atmosphere sigpatches - Updated with 9.2.0 support
* Retroarch - Updated to v1.8.4 (still no cores)
* Fake News Injector - Updated to v1.1.0
* Fusee-Primary - Updated to v0.10.4
* Quark - Updated to v0.8
* NSUSBLoader - Updated to v2.1
* Switch Backup Manager - Updated to v1.2.5
* Rekado - Updated to v3.3.4

The following packages were removed:
* ReiNX
  * The following packages dependant on ReiNX were also removed: Deltalaunch, Xorplay, SysFTPD, SwitchPresence
  * ReiNX is wildly out of date and doesn't support latest firmwares, thus I am not comfortable distributing it to users.
* ZeroTwoXCI
* Hactool and Hactoolnet
  * Since SDSetup is intended for users, I've decided to remove developer-oriented tools.

All removals are currently soft removals. This means existing share links will still select the packages (they won't show as selected on the web page but will be included in the download). This will change in the future.
