### ISSUE TITLE
Switch Web Payload Injector - 404

### ISSUE THREAD

**Issue by RaphaelDDL** [noahc3/SDSetup#175]
https://webcfw.sdsetup.com/ github page seems to have been unpublished?

![image](https://user-images.githubusercontent.com/1087109/86183583-ba6c1780-bb08-11ea-9342-a560fbd34736.png)

**Comment by tumGER** [comment]
A third-party (@lordfriky) took over it after @AtlasNX was disbanded. Unfortunately they removed the CNAME file that would allow the link to redirect to that site.

https://github.com/lordfriky/web-cfw-loader

**Comment by RaphaelDDL** [comment]
Yeah, I found that one when looking for others after posting. But just wanted to let you know since I used to use yours before. Well, good to know there's a reason. 

Thank you!

**Comment by tumGER** [comment]
I definitely agree that breaking the CNAME is questionable but neither I nor noahc3 has the power to really control that repository anymore. I'll just ping @lordfriky again in hopes of some response to this. Otherwise we could theoretically create a redirect but that isn't a great solution.

**Comment by lordfriky** [comment]
Sorry for all the inconveniences that I may have caused, I removed the CNAME because it wasn’t working when noahc3 changed his DNS provider, so I wanted to give the users an alternative to keep using it under my own GitHub Pages link

Anyway, I already restored the old CNAME, so there’s no need to use my own link anymore

Again, sorry for all the inconveniences :b

**Comment by RaphaelDDL** [comment]
No problem, thank you @lordfriky. I see it's already working again.

But I've starred yours too just in case <3
