### ISSUE TITLE
Pokémon Lets Go Pikachu Dont Start

### ISSUE THREAD

**Issue by danieltellezp** [noahc3/SDSetup#39]
Hi, today I installed Atmosphere Kosmos (v11.5/v0.8.1) (kosmos default build) but when I try to launch Pokemon Lets Go Pikachu dont start. With other CFW I can play this game (http://www.ns-atmosphere.com/en/ Atmosphere-SDFiles-080E-v1.4.zip).

My console have the 6.2 firmware.

Thx.

![errorpokemon](https://user-images.githubusercontent.com/41880878/49900631-112dd580-fe2d-11e8-9b0c-822de1867310.JPG)

**Comment by noahc3** [comment]
Sorry for late response. This is technically a Kosmos issue, so you should report the error there. However, the issue is probably due to a poorly created NSP file with modified NCA's, which Atmosphere won't boot by default. 

You might have luck by copying the atmosphere/kip_patches and atmosphere/exefs_patches folders from the files you linked into the SDSetup files.
