### ISSUE TITLE
Add package priority sorting (Option to enable nogc patches)

### ISSUE THREAD

**Issue by jayme-github** [noahc3/SDSetup#44]
Thanks for this tool!

It would be nice to have an option to include/enable nogc patches for systems updated via ChoiDujourNX.

---

* [x] Update backend to support priority sorting. nogc configs always have to be added AFTER the normal kosmos config
* [x] Fix the file zipper to not add duplicate files.

**Comment by noahc3** [comment]
I'm looking for the best way to do this, ReiNX is easy but Atmosphere is less so due to hardcoded Hekate configs. I've asked CTCaer to possibly add some option to globally enable stuff like nogc, hopefully that happens. Last thing I want to do is hardcode something to enable nogc on all of the ini files.

**Comment by noahc3** [comment]
Need to make a small tweak to the server and then I'll get this out.

**Comment by jayme-github** [comment]
With hekates `autonogc` this is probably obsolete, isn't it?

**Comment by noahc3** [comment]
Sort of but the underlying issue still remains: server needs priority support.

**Comment by noahc3** [comment]
Done.
