### ISSUE TITLE
SDSetup not loading

### ISSUE THREAD

**Issue by wolfw3** [noahc3/SDSetup#51]
I've tried loading the website on different devices, browsers, and networks, but it just hangs at the loading screen.

**Comment by noahc3** [comment]
Server is down, gimme a few minutes.

**Comment by noahc3** [comment]
There was a fibre cut at the datacenter. Site may be down for the next few hours.

**Comment by noahc3** [comment]
SDSetup was down for around 12 hours on January 27th 2019 due to a damaged fibre line to the datacenter where our server is hosted. The following changes will be implemented to mitigate issues like this in the future:

- We will spin up a second server in a different location which will mirror the first. 
    - This will ensure if one server goes down, traffic will be automatically routed to the server which is online. 
    - This also means download speeds will be faster when both servers are online as one server will be located in the US and the other in the EU, and the website will automatically select the server with the fastest network connection to your location.
- An error message will appear much quicker (currently waits 60s) if somehow both servers go offline so the user knows the server is down rather than it seeming like the website hung.

Sorry for any inconvenience!
