### ISSUE TITLE
Use Retroarch NSP instead of retroarch installer

### ISSUE THREAD

**Issue by Corgano** [noahc3/SDSetup#55]
There is more a question than a suggestion, but is there a good reason it's configured to use the regular retroarch instead of the NSP? From what I understand the NSP lets more ram be used so n64 games can run faster, shouldn't the NSP be the default? Or is there a reason the non-nsp version is used?

**Comment by noahc3** [comment]
I think most people would prefer to just use tid override for extra RAM since it protects you from being banned from having illegitimate NSP's installed.

That said, in the future (after finishing the new guide and setting up a second server) the site will have an option to include NSP versions of homebrew when they are available officially.

**Comment by Corgano** [comment]
If the preferred solution is tid override, could the pack include an installer / instructions how to do this? It's nice that the majority of things are drag-and-drop, so if the retroarch installer could do this automatically, it'd feel like a complete solution.
